#!/bin/bash

source ${AT_BASE_DIR}/utils/extra_symbols.sh
source ${AT_BASE_DIR}/utils/text.sh

# general variables
DEFAULT_TEXT_FG=${TEXT_FG_BLACK}
DEFAULT_TEXT_BG=${TEXT_BG_LIGHT_GRAY}
TEXT_SEPARATOR=' '
LEFT_PROMPT_START=${DEFAULT_TEXT_BG}${DEFAULT_TEXT_FG}
LEFT_PROMPT_END=${TEXT_STYLE_RESET_ALL}\\u${CODEPOINT_OF_BREADCRUMB_RIGHT}${TEXT_STYLE_RESET_ALL}
RIGHT_PROMPT_START="${TEXT_STYLE_REVERSE}\\u${CODEPOINT_OF_BREADCRUMB_RIGHT} ${TEXT_BG_BLACK}"
RIGHT_PROMPT_END=

# dvcs-related variables
DVCS_DETECT_ENABLED=true
DIRTY_BRANCH_TEXT_FG=${DEFAULT_TEXT_FG}
DIRTY_BRANCH_ICON=\\u${CODEPOINT_OF_BALLOT_X_HEAVY}
CLEAN_BRANCH_TEXT_FG=${DEFAULT_TEXT_FG}
CLEAN_BRANCH_ICON=\\u${CODEPOINT_OF_CHECKMARK_HEAVY}
DEFAULT_GIT_ICON=\\u${CODEPOINT_OF_LEFT_ANGLE_QUOTATION_MARK}git\\u${CODEPOINT_OF_RIGHT_ANGLE_QUOTATION_MARK}
GITHUB_ICON=\\u${CODEPOINT_OF_LEFT_ANGLE_QUOTATION_MARK}github\\u${CODEPOINT_OF_RIGHT_ANGLE_QUOTATION_MARK}
GITLAB_ICON=\\u${CODEPOINT_OF_LEFT_ANGLE_QUOTATION_MARK}gitlab\\u${CODEPOINT_OF_RIGHT_ANGLE_QUOTATION_MARK}
HG_ICON=\\u${CODEPOINT_OF_LEFT_ANGLE_QUOTATION_MARK}hg\\u${CODEPOINT_OF_RIGHT_ANGLE_QUOTATION_MARK}
BRANCH_ICON=

# cwd-related variables
CWD_DETECT_ENABLED=true
HOME_ICON=\\u${CODEPOINT_OF_TILDA}
PATH_SEPARATOR=\\u${CODEPOINT_OF_BREADCRUMB_RIGHT_OUTLINE}

# battery-related variables
BATTERY_DETECT_ENABLED=true
BATTERY_CHARGING_ICON=\\u26a1
BATTTERY_LEVEL_ICONS=(\\u${CODEPOINT_OF_BATTERY_ONE_EIGTH} \\u${CODEPOINT_OF_BATTERY_TWO_EIGTH} \\u${CODEPOINT_OF_BATTERY_THREE_EIGTH} \\u${CODEPOINT_OF_BATTERY_FOUR_EIGTH} \\u${CODEPOINT_OF_BATTERY_FIVE_EIGTH} \\u${CODEPOINT_OF_BATTERY_SIX_EIGTH} \\u${CODEPOINT_OF_BATTERY_SEVEN_EIGTH} \\u${CODEPOINT_OF_BATTERY_FULL})

# time and date related variables
DATE_ICON=
TIME_ICON=\\u23F2
